name: assistance_kit
description: tools package.
# homepage: https://www.example.com

publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=2.15.0'

dependencies:
  postgresql2: ^1.0.0                         # Edited, pool   {is Edited type_converter}
  postgres: ^2.4.5                            # transaction
  file: ^6.1.2
  http: ^0.13.4

dev_dependencies:
  test: ^1.21.4
