name: assistance_kit
description: tools package.
# homepage: https://www.example.com

version: 0.1.3
publish_to: 'none'


environment:
  sdk: '>=2.17.0'

dependencies:
  postgresql2: 1.0.3                         # Edited, pool   {is Edited type_converter}
  #postgres: 2.5.2                            # transaction
  file: ^6.1.4
  http: 0.13.5

dev_dependencies:
  test: ^1.23.1
