name: assistance_kit
description: tools package.
# homepage: https://www.example.com

version: 0.1.24
publish_to: 'none'


environment:
  sdk: '>=3.0.0'

dependencies:
  postgresql2: 1.5.1                         # Edited:{type_converter.dart}
  #postgresql2: ^1.6.2                         # Edited:{type_converter.dart}
  #postgres: 2.5.2                           # transaction
  file: ^7.0.0
  http: ^1.2.1

dev_dependencies:
  test: any
  lint: any
